// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCBDDpL4I3n1GpkeFAYfbNFR3KTl6iMQ2E',
    appId: '1:951859681263:web:ed57e9d8f2dc9f271cc81a',
    messagingSenderId: '951859681263',
    projectId: 'checkin-a507c',
    authDomain: 'checkin-a507c.firebaseapp.com',
    storageBucket: 'checkin-a507c.firebasestorage.app',
    measurementId: 'G-G4Y4EQ5HC6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAnYxep6KpQa8EFsoSGbJiG_oZwK6Vqa14',
    appId: '1:951859681263:android:17d2d0be24e5250d1cc81a',
    messagingSenderId: '951859681263',
    projectId: 'checkin-a507c',
    storageBucket: 'checkin-a507c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAjVntm5HqCVPQVwGOsqpP40a_8BKpIwwA',
    appId: '1:951859681263:ios:e2c1b1be7e0f12791cc81a',
    messagingSenderId: '951859681263',
    projectId: 'checkin-a507c',
    storageBucket: 'checkin-a507c.firebasestorage.app',
    iosBundleId: 'com.example.appCheckin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAjVntm5HqCVPQVwGOsqpP40a_8BKpIwwA',
    appId: '1:951859681263:ios:e2c1b1be7e0f12791cc81a',
    messagingSenderId: '951859681263',
    projectId: 'checkin-a507c',
    storageBucket: 'checkin-a507c.firebasestorage.app',
    iosBundleId: 'com.example.appCheckin',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCBDDpL4I3n1GpkeFAYfbNFR3KTl6iMQ2E',
    appId: '1:951859681263:web:53fd5d69d5d51d7d1cc81a',
    messagingSenderId: '951859681263',
    projectId: 'checkin-a507c',
    authDomain: 'checkin-a507c.firebaseapp.com',
    storageBucket: 'checkin-a507c.firebasestorage.app',
    measurementId: 'G-9RJ92ZGERK',
  );
}
